---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jellyfin-tls
  namespace: media
spec:
  secretName: jellyfin-tls
  dnsNames:
    - media.greiner.home
  issuerRef:
    kind: ClusterIssuer
    name: greiner-ca-issuer
