apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: "kube-system-secure-headers@kubernetescrd"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - media.greiner.home
      secretName: jellyfin-tls
  rules:
    - host: media.greiner.home
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jellyfin
                port:
                  number: 80