apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
  namespace: jellyfin
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  volumeName: jellyfin-config-pv