apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pv-media.yaml
  - pvc-media.yaml
  - pv-jellyfin-config.yaml
  - pvc-jellyfin-config.yaml
  - pv-lidarr-config.yaml
  - pvc-lidarr-config.yaml
  - pv-prowlar-config.yaml
  - pvc-prowlar-config.yaml
  - pv-sonarr-config.yaml
  - pvc-sonarr-config.yaml
  - pv-radarr-config.yaml
  - pvc-radarr-config.yaml
  - pv-qbittorrent-config.yaml
  - pvc-qbittorrent-config.yaml
  - pv-pictures.yaml
  - pvc-pictures.yaml
  - pv-uploads.yaml
  - pvc-uploads.yaml