apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-pv
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  hostPath:
    path: /data1/media
    type: DirectoryOrCreate