apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-config-pv
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/charles/k8s-data/radarr-config
    type: DirectoryOrCreate
