---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config
  namespace: media
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  storageClassName: ""
  volumeName: prowlarr-config-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi