apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-music-pvc
  namespace: media
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: media-music-pv