apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: vault

  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.32.0

    helm:
      values: |
        server:
          standalone:
            enabled: true

          dataStorage:
            enabled: true
            size: 5Gi

          resources:
            requests:
              cpu: 100m
              memory: 256Mi

        ui:
          enabled: true

  syncPolicy:
    automated:
      prune: false   # IMPORTANT SAFETY SWITCH
      selfHeal: true
    syncOptions:
      - CreateNamespace=false