apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-server
  namespace: immich
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-server
  template:
    metadata:
      labels:
        app: immich-server
    spec:
      containers:
        - name: immich
          image: ghcr.io/immich-app/immich-server:v2.7.5
          ports:
            - containerPort: 3001
          env:
            - name: DB_HOSTNAME
              value: immich-postgres
            - name: DB_USERNAME
              value: immich
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich-secret
                  key: DB_PASSWORD
            - name: DB_DATABASE_NAME
              value: immich
            - name: REDIS_HOSTNAME
              value: immich-redis
            - name: IMMICH_SERVER_URL
              value: https://photos.greiner.home
            - name: IMMICH_HOST
              value: "0.0.0.0"
            - name: IMMICH_PORT
              value: "3001"
            - name: UPLOAD_LOCATION
              value: /usr/src/app/upload
            - name: OIDC_ENABLED
              value: "true"
            - name: OIDC_ISSUER_URL
              value: "https://idp.greiner.nu/realms/greiner"
            - name: OIDC_CLIENT_ID
              value: "immich-home"
            - name: OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: immich-secret
                  key: OIDC_CLIENT_SECRET
            - name: OIDC_SCOPE
              value: "openid profile email"
            - name: OIDC_AUTO_REGISTER
              value: "true"
            - name: OIDC_BUTTON_TEXT
              value: "Login with Keycloak"

          volumeMounts:
            - name: uploads
              mountPath: /usr/src/app/upload
            - name: pictures
              mountPath: /mnt/pictures
              readOnly: true
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: immich-uploads
        - name: pictures
          persistentVolumeClaim:
            claimName: immich-pictures