apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-secret
  namespace: immich
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: immich-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: immich
        property: DB_PASSWORD

    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: immich
        property: OIDC_CLIENT_SECRET