apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: immich
spec:
  provider:
    vault:
      server: "https://vault.greiner.home"
      path: "secret"
      version: "v2"
      caProvider:
        type: Secret
        name: vault-ca
        key: ca.crt
      auth:
        tokenSecretRef:
          name: vault-token
          key: token