apiVersion: batch/v1
kind: Job
metadata:
  name: immich-import
  namespace: immich
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: immich-cli
          image: ghcr.io/immich-app/immich-cli:latest
          command: ["immich"]
          args:
            - upload
            - --recursive
            - --ignore
            - ".DS_Store"
            - /import
          env:
            - name: IMMICH_SERVER_URL
              value: "https://photos.greiner.home"
            - name: IMMICH_API_KEY
              valueFrom:
                secretKeyRef:
                  name: immich-secret
                  key: IMMICH_API_KEY
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0"
          volumeMounts:
            - name: pictures
              mountPath: /import
              readOnly: true
      volumes:
        - name: pictures
          persistentVolumeClaim:
            claimName: immich-pictures