spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - photos.greiner.home
      secretName: immich-tls
  rules:
    - host: photos.greiner.home
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: immich-server
                port:
                  number: 80