apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-config-pv
  namespace: immich
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: immich-config-pv