apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-pictures
  namespace: immich
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: immich-media-pv