apiVersion: v1
kind: PersistentVolume
metadata:
  name: prowlarr-config-pv
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  storageClassName: ""
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data1/prowlarr
