apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: woodpecker-github-oauth
  namespace: woodpecker
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: woodpecker-github-oauth
    creationPolicy: Owner
  data:
    - secretKey: WOODPECKER_GITHUB_CLIENT
      remoteRef:
        key: woodpecker
        property: GITHUB_CLIENT
    - secretKey: WOODPECKER_GITHUB_SECRET
      remoteRef:
        key: woodpecker
        property: GITHUB_CLIENT_SECRET