apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-github-token
  namespace: woodpecker
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: renovate-github-token
    creationPolicy: Owner
  data:
    - secretKey: RENOVATE_TOKEN
      remoteRef:
        key: woodpecker
        property: RENOVATE_TOKEN