apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-tls
  namespace: vault
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  secretName: vault-tls

  subject:
    organizations:
      - greiner

  commonName: vault.greiner.home

  dnsNames:
    - vault.greiner.home

  issuerRef:
    name: greiner-ca-issuer
    kind: ClusterIssuer