---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  replicas: 1

  selector:
    matchLabels:
      app: homeassistant

  template:
    metadata:
      labels:
        app: homeassistant

    spec:
      initContainers:
        - name: install-config
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              cp /config-source/configuration.yaml /config/configuration.yaml
          volumeMounts:
            - name: config
              mountPath: /config
            - name: config-source
              mountPath: /config-source
              readOnly: true

      containers:
        - name: homeassistant
          image: ghcr.io/home-assistant/home-assistant:2026.8.3

          ports:
            - name: http
              containerPort: 8123

          volumeMounts:
            - name: config
              mountPath: /config

          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 1Gi

      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: homeassistant-config

        - name: config-source
          configMap:
            name: homeassistant-config