---
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: homeassistant-config
    files:
      - configuration.yaml
      - solaredge-template.yaml
      - automations.yaml
      - scripts.yaml
      - scenes.yaml
      - solar-dashboard.yaml
replacements:
  - source:
      kind: ConfigMap
      name: homeassistant-config
      fieldPath: metadata.name
    targets:
      - select:
          kind: Deployment
          name: homeassistant
        fieldPaths:
          - spec.template.spec.volumes.[name=config-source].configMap.name
resources:
  - certificate.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pvc.yaml