---
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: homeassistant-config
    files:
      - configuration.yaml

resources:
  - certificate.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pvc.yaml